### PR TITLE
create a new file and add content

### PR DESCRIPTION
**Pull request by Micosnow**
# Title

On the title describe
what you've fixed (or created) with this Pull Request (PR).

## Summary

Insert a short (one or two sentence) summary here.

Fixes #Issue_Number

>Note: The "Fixes #nnn" syntax in the PR description causes
>GitHub to automatically close the issue when this PR is merged.
> Remove that line if you don't have issues associated with this
> PR. Click on the Guidelines for Contributing link above for details.

## Details

Explain your changes, and why you made them. If that
information is already available in the issue referenced
above, just referencing the issue is preferred to copying
the text.

This may not be necessary depending on the scope of the PR 
changes. For example, "fix typo in introduction.md" is
sufficient to describe that PR.

## Suggested Reviewers

If you know who should review this, use '@' to request a review.

### CODE REVIEW

**Comment by luyajun0205** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[test.md](https://github.com/OPS-E2E-Prod/docs/blob/prtest_branch/test.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C4%5C14%5Cffa6e1d7-ed5e-6f48-8206-aa74b2c4e1ab%5CPullRequest%5C201704140327181127-2%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-susu** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/TestingPullRequest.md](https://github.com/OPS-E2E-Prod/docs/blob/prtest_branch/docs/TestingPullRequest.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/e2eprod-core-docs/articles/testingpullrequest?branch=pr-en-us-2) | [Details](#user-content-docs%2FTestingPullRequest.md)
[docs/test.md](https://github.com/OPS-E2E-Prod/docs/blob/prtest_branch/docs/test.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-core-docs/articles/test?branch=pr-en-us-2) |
[docs/testfile.md](https://github.com/OPS-E2E-Prod/docs/blob/prtest_branch/docs/testfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-core-docs/articles/testfile?branch=pr-en-us-2) |
[test.md](https://github.com/OPS-E2E-Prod/docs/blob/prtest_branch/test.md) | :white_check_mark:Succeeded | |

<a name="docs%2FTestingPullRequest.md"></a>
### [docs/TestingPullRequest.md](https://github.com/OPS-E2E-Prod/docs/blob/prtest_branch/docs/TestingPullRequest.md)
 - **Line 4**: **[Warning]** Invalid file link:(~/nonexisted1.md).
 - **Line 5**: **[Warning]** Invalid file link:(~/nonexisted2.md).
 - **Line 6**: **[Warning]** Invalid file link:(~/nonexisted3.md).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C5%5C4%5Cffa6e1d7-ed5e-6f48-8206-aa74b2c4e1ab%5CPullRequest%5C201705040258258708-2%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-peliao** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/TestingPullRequest.md](https://github.com/OPS-E2E-Prod/docs/blob/prtest_branch/docs/TestingPullRequest.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/e2eprod-core-docs/articles/testingpullrequest?branch=pr-en-us-2) | [Details](#user-content-docs%2FTestingPullRequest.md)
[docs/test.md](https://github.com/OPS-E2E-Prod/docs/blob/prtest_branch/docs/test.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-core-docs/articles/test?branch=pr-en-us-2) |
[docs/testfile.md](https://github.com/OPS-E2E-Prod/docs/blob/prtest_branch/docs/testfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-core-docs/articles/testfile?branch=pr-en-us-2) |
[test.md](https://github.com/OPS-E2E-Prod/docs/blob/prtest_branch/test.md) | :white_check_mark:Succeeded | |

<a name="docs%2FTestingPullRequest.md"></a>
### [docs/TestingPullRequest.md](https://github.com/OPS-E2E-Prod/docs/blob/prtest_branch/docs/TestingPullRequest.md)
 - **Line 4**: **[Warning]** Invalid file link:(~/nonexisted1.md).
 - **Line 5**: **[Warning]** Invalid file link:(~/nonexisted2.md).
 - **Line 6**: **[Warning]** Invalid file link:(~/nonexisted3.md).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C5%5C4%5Cffa6e1d7-ed5e-6f48-8206-aa74b2c4e1ab%5CPullRequest%5C201705040258354314-2%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-susu** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/TestingPullRequest.md](https://github.com/OPS-E2E-Prod/docs/blob/prtest_branch/docs/TestingPullRequest.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/e2eprod-core-docs/articles/testingpullrequest?branch=pr-en-us-2) | [Details](#user-content-docs%2FTestingPullRequest.md)
[docs/test.md](https://github.com/OPS-E2E-Prod/docs/blob/prtest_branch/docs/test.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-core-docs/articles/test?branch=pr-en-us-2) |
[docs/testfile.md](https://github.com/OPS-E2E-Prod/docs/blob/prtest_branch/docs/testfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-core-docs/articles/testfile?branch=pr-en-us-2) |
[test.md](https://github.com/OPS-E2E-Prod/docs/blob/prtest_branch/test.md) | :white_check_mark:Succeeded | |

<a name="docs%2FTestingPullRequest.md"></a>
### [docs/TestingPullRequest.md](https://github.com/OPS-E2E-Prod/docs/blob/prtest_branch/docs/TestingPullRequest.md)
 - **Line 4**: **[Warning]** Invalid file link:(~/nonexisted1.md).
 - **Line 5**: **[Warning]** Invalid file link:(~/nonexisted2.md).
 - **Line 6**: **[Warning]** Invalid file link:(~/nonexisted3.md).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C5%5C4%5Cffa6e1d7-ed5e-6f48-8206-aa74b2c4e1ab%5CPullRequest%5C201705040629086934-2%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by luyajun0205** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/TestingPullRequest.md](https://github.com/OPS-E2E-Prod/docs/blob/prtest_branch/docs/TestingPullRequest.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/e2eprod-core-docs/articles/testingpullrequest?branch=pr-en-us-2) | [Details](#user-content-docs%2FTestingPullRequest.md)
[docs/test.md](https://github.com/OPS-E2E-Prod/docs/blob/prtest_branch/docs/test.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-core-docs/articles/test?branch=pr-en-us-2) |
[docs/testfile.md](https://github.com/OPS-E2E-Prod/docs/blob/prtest_branch/docs/testfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-core-docs/articles/testfile?branch=pr-en-us-2) |
[test.md](https://github.com/OPS-E2E-Prod/docs/blob/prtest_branch/test.md) | :white_check_mark:Succeeded | |

<a name="docs%2FTestingPullRequest.md"></a>
### [docs/TestingPullRequest.md](https://github.com/OPS-E2E-Prod/docs/blob/prtest_branch/docs/TestingPullRequest.md)
 - **Line 4**: **[Warning]** Invalid file link:(~/nonexisted1.md).
 - **Line 5**: **[Warning]** Invalid file link:(~/nonexisted2.md).
 - **Line 6**: **[Warning]** Invalid file link:(~/nonexisted3.md).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C5%5C4%5Cffa6e1d7-ed5e-6f48-8206-aa74b2c4e1ab%5CPullRequest%5C201705041250033475-2%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
